import { imbuimentData } from "@/components/imbuiments/@types/imbuiments";

export const IMBUIMENTS_DATA: imbuimentData[] = [
  {
    name: "Featherweight",
    icon: "/images/imbuiments/featherweight/Featherweight.gif",
    category: "support",
    itens: [
      {
        name: "Fairy Wings",
        qtty: 20,
        icon: "/images/imbuiments/featherweight/Fairy_Wings.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Little Bowl of Myrrh",
        qtty: 10,
        icon: "/images/imbuiments/featherweight/Little_Bowl_of_Myrrh.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Goosebump Leather",
        qtty: 5,
        icon: "/images/imbuiments/featherweight/Goosebump_Leather.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Strike",
    icon: "/images/imbuiments/strike/Strike.gif",
    category: "support",
    itens: [
      {
        name: "Protective Charm",
        qtty: 20,
        icon: "/images/imbuiments/strike/Protective_Charm.gif",
        type: "basic",
        amount: 15,
        chance: 10,
      },
      {
        name: "Sabretooth",
        qtty: 25,
        icon: "/images/imbuiments/strike/Sabretooth.gif",
        type: "intricate",
        amount: 25,
        chance: 10,
      },
      {
        name: "Vexclaw Talon",
        qtty: 5,
        icon: "/images/imbuiments/strike/Vexclaw_Talon.gif",
        type: "powerful",
        amount: 50,
        chance: 10,
      },
    ],
  },
  {
    name: "Swiftness",
    icon: "/images/imbuiments/swiftness/Swiftness.gif",
    category: "support",
    itens: [
      {
        name: "Damselfly Wing",
        qtty: 15,
        icon: "/images/imbuiments/swiftness/Damselfly_Wing.gif",
        type: "basic",
        amount: 10,
        chance: null,
      },
      {
        name: "Compass",
        qtty: 25,
        icon: "/images/imbuiments/swiftness/Compass.gif",
        type: "intricate",
        amount: 15,
        chance: null,
      },
      {
        name: "Waspoid Wing",
        qtty: 20,
        icon: "/images/imbuiments/swiftness/Waspoid_Wing.gif",
        type: "powerful",
        amount: 30,
        chance: null,
      },
    ],
  },
  {
    name: "Vampirism",
    icon: "/images/imbuiments/vampirism/Vampirism.gif",
    category: "support",
    itens: [
      {
        name: "Vampire Teeth",
        qtty: 25,
        icon: "/images/imbuiments/vampirism/Vampire_Teeth.gif",
        type: "basic",
        amount: 5,
        chance: null,
      },
      {
        name: "Bloody Pincers",
        qtty: 15,
        icon: "/images/imbuiments/vampirism/Bloody_Pincers.gif",
        type: "intricate",
        amount: 10,
        chance: null,
      },
      {
        name: "Piece of Dead Brain",
        qtty: 5,
        icon: "/images/imbuiments/vampirism/Piece_of_Dead_Brain.gif",
        type: "powerful",
        amount: 25,
        chance: null,
      },
    ],
  },
  {
    name: "Vibrancy",
    icon: "/images/imbuiments/vibrancy/Vibrancy.gif",
    category: "support",
    itens: [
      {
        name: "Wereboar Hooves",
        qtty: 20,
        icon: "/images/imbuiments/vibrancy/Wereboar_Hooves.gif",
        type: "basic",
        amount: 15,
        chance: null,
      },
      {
        name: "Crystallized Anger",
        qtty: 15,
        icon: "/images/imbuiments/vibrancy/Crystallized_Anger.gif",
        type: "intricate",
        amount: 25,
        chance: null,
      },
      {
        name: "Quill",
        qtty: 5,
        icon: "/images/imbuiments/vibrancy/Quill.gif",
        type: "powerful",
        amount: 50,
        chance: null,
      },
    ],
  },
  {
    name: "Void",
    icon: "/images/imbuiments/void/Void.gif",
    category: "support",
    itens: [
      {
        name: "Rope Belt",
        qtty: 25,
        icon: "/images/imbuiments/void/Rope_Belt.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Silencer Claws",
        qtty: 25,
        icon: "/images/imbuiments/void/Silencer_Claws.gif",
        type: "intricate",
        amount: 5,
        chance: null,
      },
      {
        name: "Some Grimeleech Wings",
        qtty: 5,
        icon: "/images/imbuiments/void/Some_Grimeleech_Wings.gif",
        type: "powerful",
        amount: 8,
        chance: null,
      },
    ],
  },
  {
    name: "Cloud Fabric",
    icon: "/images/imbuiments/cloud-fabric/Cloud_Fabric.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Wyvern Talisman",
        qtty: 20,
        icon: "/images/imbuiments/cloud-fabric/Wyvern_Talisman.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Crawler Head Plating",
        qtty: 15,
        icon: "/images/imbuiments/cloud-fabric/Crawler_Head_Plating.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Wyrm Scale",
        qtty: 10,
        icon: "/images/imbuiments/cloud-fabric/Wyrm_Scale.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Demon Presence",
    icon: "/images/imbuiments/demon-presence/Demon_Presence.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Cultish Robe",
        qtty: 25,
        icon: "/images/imbuiments/demon-presence/Cultish_Robe.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Cultish Mask",
        qtty: 25,
        icon: "/images/imbuiments/demon-presence/Cultish_Mask.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Hellspawn Tail",
        qtty: 20,
        icon: "/images/imbuiments/demon-presence/Hellspawn_Tail.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Dragon Hide",
    icon: "/images/imbuiments/dragon-hide/Dragon_Hide.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Green Dragon Leather",
        qtty: 20,
        icon: "/images/imbuiments/dragon-hide/Green_Dragon_Leather.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Blazing Bone",
        qtty: 10,
        icon: "/images/imbuiments/dragon-hide/Blazing_Bone.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Draken Sulphur",
        qtty: 5,
        icon: "/images/imbuiments/dragon-hide/Draken_Sulphur.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Lich Shroud",
    icon: "/images/imbuiments/lich-shroud/Lich_Shroud.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Flask of Embalming Fluid",
        qtty: 25,
        icon: "/images/imbuiments/lich-shroud/Flask_of_Embalming_Fluid.gif",
        type: "basic",
        amount: 2,
        chance: null,
      },
      {
        name: "Gloom Wolf Fur",
        qtty: 20,
        icon: "/images/imbuiments/lich-shroud/Gloom_Wolf_Fur.gif",
        type: "intricate",
        amount: 5,
        chance: null,
      },
      {
        name: "Mystical Hourglass",
        qtty: 5,
        icon: "/images/imbuiments/lich-shroud/Mystical_Hourglass.gif",
        type: "powerful",
        amount: 10,
        chance: null,
      },
    ],
  },
  {
    name: "Quara Scale",
    icon: "/images/imbuiments/quara-scale/Quara_Scale.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Winter Wolf Fur",
        qtty: 25,
        icon: "/images/imbuiments/quara-scale/Winter_Wolf_Fur.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Thick Fur",
        qtty: 15,
        icon: "/images/imbuiments/quara-scale/Thick_Fur.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Deepling Warts",
        qtty: 10,
        icon: "/images/imbuiments/quara-scale/Deepling_Warts.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Snake Skin",
    icon: "/images/imbuiments/snake-skin/Snake_Skin_icon.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Piece of Swampling Wood",
        qtty: 25,
        icon: "/images/imbuiments/snake-skin/Piece_of_Swampling_Wood.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Snake Skin",
        qtty: 20,
        icon: "/images/imbuiments/snake-skin/Snake_Skin.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Brimstone Fangs",
        qtty: 10,
        icon: "/images/imbuiments/snake-skin/Brimstone_Fangs.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
];
