import { imbuimentData } from "@/components/imbuiments/@types/imbuiments";

export const IMBUIMENTS_DATA: imbuimentData[] = [
  {
    name: "Featherweight",
    icon: "/images/imbuiments/featherweight/Featherweight.gif",
    category: "support",
    itens: [
      {
        name: "Fairy Wings",
        qtty: 20,
        icon: "/images/imbuiments/featherweight/Fairy_Wings.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Little Bowl of Myrrh",
        qtty: 10,
        icon: "/images/imbuiments/featherweight/Little_Bowl_of_Myrrh.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Goosebump Leather",
        qtty: 5,
        icon: "/images/imbuiments/featherweight/Goosebump_Leather.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Strike",
    icon: "/images/imbuiments/strike/Strike.gif",
    category: "support",
    itens: [
      {
        name: "Protective Charm",
        qtty: 20,
        icon: "/images/imbuiments/strike/Protective_Charm.gif",
        type: "basic",
        amount: 15,
        chance: 10,
      },
      {
        name: "Sabretooth",
        qtty: 25,
        icon: "/images/imbuiments/strike/Sabretooth.gif",
        type: "intricate",
        amount: 25,
        chance: 10,
      },
      {
        name: "Vexclaw Talon",
        qtty: 5,
        icon: "/images/imbuiments/strike/Vexclaw_Talon.gif",
        type: "powerful",
        amount: 50,
        chance: 10,
      },
    ],
  },
  {
    name: "Swiftness",
    icon: "/images/imbuiments/swiftness/Swiftness.gif",
    category: "support",
    itens: [
      {
        name: "Damselfly Wing",
        qtty: 15,
        icon: "/images/imbuiments/swiftness/Damselfly_Wing.gif",
        type: "basic",
        amount: 10,
        chance: null,
      },
      {
        name: "Compass",
        qtty: 25,
        icon: "/images/imbuiments/swiftness/Compass.gif",
        type: "intricate",
        amount: 15,
        chance: null,
      },
      {
        name: "Waspoid Wing",
        qtty: 20,
        icon: "/images/imbuiments/swiftness/Waspoid_Wing.gif",
        type: "powerful",
        amount: 30,
        chance: null,
      },
    ],
  },
  {
    name: "Vampirism",
    icon: "/images/imbuiments/vampirism/Vampirism.gif",
    category: "support",
    itens: [
      {
        name: "Vampire Teeth",
        qtty: 25,
        icon: "/images/imbuiments/vampirism/Vampire_Teeth.gif",
        type: "basic",
        amount: 5,
        chance: null,
      },
      {
        name: "Bloody Pincers",
        qtty: 15,
        icon: "/images/imbuiments/vampirism/Bloody_Pincers.gif",
        type: "intricate",
        amount: 10,
        chance: null,
      },
      {
        name: "Piece of Dead Brain",
        qtty: 5,
        icon: "/images/imbuiments/vampirism/Piece_of_Dead_Brain.gif",
        type: "powerful",
        amount: 25,
        chance: null,
      },
    ],
  },
  {
    name: "Vibrancy",
    icon: "/images/imbuiments/vibrancy/Vibrancy.gif",
    category: "support",
    itens: [
      {
        name: "Wereboar Hooves",
        qtty: 20,
        icon: "/images/imbuiments/vibrancy/Wereboar_Hooves.gif",
        type: "basic",
        amount: 15,
        chance: null,
      },
      {
        name: "Crystallized Anger",
        qtty: 15,
        icon: "/images/imbuiments/vibrancy/Crystallized_Anger.gif",
        type: "intricate",
        amount: 25,
        chance: null,
      },
      {
        name: "Quill",
        qtty: 5,
        icon: "/images/imbuiments/vibrancy/Quill.gif",
        type: "powerful",
        amount: 50,
        chance: null,
      },
    ],
  },
  {
    name: "Void",
    icon: "/images/imbuiments/void/Void.gif",
    category: "support",
    itens: [
      {
        name: "Rope Belt",
        qtty: 25,
        icon: "/images/imbuiments/void/Rope_Belt.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Silencer Claws",
        qtty: 25,
        icon: "/images/imbuiments/void/Silencer_Claws.gif",
        type: "intricate",
        amount: 5,
        chance: null,
      },
      {
        name: "Some Grimeleech Wings",
        qtty: 5,
        icon: "/images/imbuiments/void/Some_Grimeleech_Wings.gif",
        type: "powerful",
        amount: 8,
        chance: null,
      },
    ],
  },
  {
    name: "Cloud Fabric",
    icon: "/images/imbuiments/cloud-fabric/Cloud_Fabric.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Wyvern Talisman",
        qtty: 20,
        icon: "/images/imbuiments/cloud-fabric/Wyvern_Talisman.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Crawler Head Plating",
        qtty: 15,
        icon: "/images/imbuiments/cloud-fabric/Crawler_Head_Plating.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Wyrm Scale",
        qtty: 10,
        icon: "/images/imbuiments/cloud-fabric/Wyrm_Scale.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Demon Presence",
    icon: "/images/imbuiments/demon-presence/Demon_Presence.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Cultish Robe",
        qtty: 25,
        icon: "/images/imbuiments/demon-presence/Cultish_Robe.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Cultish Mask",
        qtty: 25,
        icon: "/images/imbuiments/demon-presence/Cultish_Mask.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Hellspawn Tail",
        qtty: 20,
        icon: "/images/imbuiments/demon-presence/Hellspawn_Tail.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Dragon Hide",
    icon: "/images/imbuiments/dragon-hide/Dragon_Hide.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Green Dragon Leather",
        qtty: 20,
        icon: "/images/imbuiments/dragon-hide/Green_Dragon_Leather.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Blazing Bone",
        qtty: 10,
        icon: "/images/imbuiments/dragon-hide/Blazing_Bone.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Draken Sulphur",
        qtty: 5,
        icon: "/images/imbuiments/dragon-hide/Draken_Sulphur.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Lich Shroud",
    icon: "/images/imbuiments/lich-shroud/Lich_Shroud.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Flask of Embalming Fluid",
        qtty: 25,
        icon: "/images/imbuiments/lich-shroud/Flask_of_Embalming_Fluid.gif",
        type: "basic",
        amount: 2,
        chance: null,
      },
      {
        name: "Gloom Wolf Fur",
        qtty: 20,
        icon: "/images/imbuiments/lich-shroud/Gloom_Wolf_Fur.gif",
        type: "intricate",
        amount: 5,
        chance: null,
      },
      {
        name: "Mystical Hourglass",
        qtty: 5,
        icon: "/images/imbuiments/lich-shroud/Mystical_Hourglass.gif",
        type: "powerful",
        amount: 10,
        chance: null,
      },
    ],
  },
  {
    name: "Quara Scale",
    icon: "/images/imbuiments/quara-scale/Quara_Scale.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Winter Wolf Fur",
        qtty: 25,
        icon: "/images/imbuiments/quara-scale/Winter_Wolf_Fur.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Thick Fur",
        qtty: 15,
        icon: "/images/imbuiments/quara-scale/Thick_Fur.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Deepling Warts",
        qtty: 10,
        icon: "/images/imbuiments/quara-scale/Deepling_Warts.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Snake Skin",
    icon: "/images/imbuiments/snake-skin/Snake_Skin_icon.gif",
    category: "elemental protection",
    itens: [
      {
        name: "Piece of Swampling Wood",
        qtty: 25,
        icon: "/images/imbuiments/snake-skin/Piece_of_Swampling_Wood.gif",
        type: "basic",
        amount: 3,
        chance: null,
      },
      {
        name: "Snake Skin",
        qtty: 20,
        icon: "/images/imbuiments/snake-skin/Snake_Skin.gif",
        type: "intricate",
        amount: 8,
        chance: null,
      },
      {
        name: "Brimstone Fangs",
        qtty: 10,
        icon: "/images/imbuiments/snake-skin/Brimstone_Fangs.gif",
        type: "powerful",
        amount: 15,
        chance: null,
      },
    ],
  },
  {
    name: "Bash",
    icon: "/images/imbuiments/bash/Bash.gif",
    category: "skill",
    itens: [
      {
        name: "Cyclops Toe",
        qtty: 20,
        icon: "/images/imbuiments/bash/Cyclops_Toe.gif",
        type: "basic",
        amount: 1,
        chance: null,
      },
      {
        name: "Ogre Nose Ring",
        qtty: 15,
        icon: "/images/imbuiments/bash/Ogre_Nose_Ring.gif",
        type: "intricate",
        amount: 2,
        chance: null,
      },
      {
        name: "Warmaster's Wristguards",
        qtty: 10,
        icon: "/images/imbuiments/bash/Warmaster's_Wristguards.gif",
        type: "powerful",
        amount: 4,
        chance: null,
      },
    ],
  },
  {
    name: "Blockade",
    icon: "/images/imbuiments/blockade/Blockade.gif",
    category: "skill",
    itens: [
      {
        name: "Piece of Scarab Shell",
        qtty: 20,
        icon: "/images/imbuiments/blockade/Piece_of_Scarab_Shell.gif",
        type: "basic",
        amount: 1,
        chance: null,
      },
      {
        name: "Brimstone Shell",
        qtty: 25,
        icon: "/images/imbuiments/blockade/Brimstone_Shell.gif",
        type: "intricate",
        amount: 2,
        chance: null,
      },
      {
        name: "Frazzle Skin",
        qtty: 25,
        icon: "/images/imbuiments/blockade/Frazzle_Skin.gif",
        type: "powerful",
        amount: 4,
        chance: null,
      },
    ],
  },
  {
    name: "Chop",
    icon: "/images/imbuiments/chop/chop.gif",
    category: "skill",
    itens: [
      {
        name: "Orc Tooth",
        qtty: 20,
        icon: "/images/imbuiments/chop/Orc_Tooth.gif",
        type: "basic",
        amount: 1,
        chance: null,
      },
      {
        name: "Battle Stone",
        qtty: 25,
        icon: "/images/imbuiments/chop/Battle_Stone.gif",
        type: "intricate",
        amount: 2,
        chance: null,
      },
      {
        name: "Moohtant Horn",
        qtty: 20,
        icon: "/images/imbuiments/chop/Moohtant_Horn.gif",
        type: "powerful",
        amount: 4,
        chance: null,
      },
    ],
  },
  {
    name: "Epiphany",
    icon: "/images/imbuiments/epiphany/Epiphany.gif",
    category: "skill",
    itens: [
      {
        name: "Elvish Talisman",
        qtty: 25,
        icon: "/images/imbuiments/epiphany/Elvish_Talisman.gif",
        type: "basic",
        amount: 1,
        chance: null,
      },
      {
        name: "Broken Shamanic Staff",
        qtty: 15,
        icon: "/images/imbuiments/epiphany/Broken_Shamanic_Staff.gif",
        type: "intricate",
        amount: 2,
        chance: null,
      },
      {
        name: "Strand of Medusa Hair",
        qtty: 15,
        icon: "/images/imbuiments/epiphany/Strand_of_Medusa_Hair.gif",
        type: "powerful",
        amount: 4,
        chance: null,
      },
    ],
  },
  {
    name: "Precision",
    icon: "/images/imbuiments/precision/Precision.gif",
    category: "skill",
    itens: [
      {
        name: "Elven Scouting Glass",
        qtty: 25,
        icon: "/images/imbuiments/precision/Elven_Scouting_Glass.gif",
        type: "basic",
        amount: 1,
        chance: null,
      },
      {
        name: "Elven Hoof",
        qtty: 20,
        icon: "/images/imbuiments/precision/Elven_Hoof.gif",
        type: "intricate",
        amount: 2,
        chance: null,
      },
      {
        name: "Metal Spike",
        qtty: 10,
        icon: "/images/imbuiments/precision/Metal_Spike.gif",
        type: "powerful",
        amount: 4,
        chance: null,
      },
    ],
  },
  {
    name: "lash",
    icon: "/images/imbuiments/lash/Lash.gif",
    category: "skill",
    itens: [
      {
        name: "Lion's Mane",
        qtty: 25,
        icon: "/images/imbuiments/lash/Lion's_Mane.gif",
        type: "basic",
        amount: 1,
        chance: null,
      },
      {
        name: "Mooh'tah Shell",
        qtty: 25,
        icon: "/images/imbuiments/lash/Mooh'tah_Shell.gif",
        type: "intricate",
        amount: 2,
        chance: null,
      },
      {
        name: "War Crystal",
        qtty: 5,
        icon: "/images/imbuiments/lash/War_Crystal.gif",
        type: "powerful",
        amount: 4,
        chance: null,
      },
    ],
  },
  {
    name: "Electrify",
    icon: "/images/imbuiments/electrify/Electrify.gif",
    category: "elemental damage",
    itens: [
      {
        name: "Rorc Feather",
        qtty: 25,
        icon: "/images/imbuiments/electrify/Rorc_Feather.gif",
        type: "basic",
        amount: 10,
        chance: null,
      },
      {
        name: "Peacock Feather Fan",
        qtty: 5,
        icon: "/images/imbuiments/electrify/Peacock_Feather_Fan.gif",
        type: "intricate",
        amount: 25,
        chance: null,
      },
      {
        name: "Energy Vein",
        qtty: 1,
        icon: "/images/imbuiments/electrify/Energy_Vein.gif",
        type: "powerful",
        amount: 50,
        chance: null,
      },
    ],
  },
  {
    name: "Frost",
    icon: "/images/imbuiments/frost/Frost.gif",
    category: "elemental damage",
    itens: [
      {
        name: "Frosty Heart",
        qtty: 25,
        icon: "/images/imbuiments/frost/Frosty_Heart.gif",
        type: "basic",
        amount: 10,
        chance: null,
      },
      {
        name: "Seacrest Hair",
        qtty: 10,
        icon: "/images/imbuiments/frost/Seacrest_Hair.gif",
        type: "intricate",
        amount: 25,
        chance: null,
      },
      {
        name: "Polar Bear Paw",
        qtty: 5,
        icon: "/images/imbuiments/frost/Polar_Bear_Paw.gif",
        type: "powerful",
        amount: 50,
        chance: null,
      },
    ],
  },
  {
    name: "Reap",
    icon: "/images/imbuiments/reap/Reap.gif",
    category: "elemental damage",
    itens: [
      {
        name: "Pile of Grave Earth",
        qtty: 25,
        icon: "/images/imbuiments/reap/Pile_of_Grave_Earth.gif",
        type: "basic",
        amount: 10,
        chance: null,
      },
      {
        name: "Demonic Skeletal Hand",
        qtty: 20,
        icon: "/images/imbuiments/reap/Demonic_Skeletal_Hand.gif",
        type: "intricate",
        amount: 25,
        chance: null,
      },
      {
        name: "Petrified Scream",
        qtty: 5,
        icon: "/images/imbuiments/reap/Petrified_Scream.gif",
        type: "powerful",
        amount: 50,
        chance: null,
      },
    ],
  },
  {
    name: "Scorch",
    icon: "/images/imbuiments/scorch/Scorch.gif",
    category: "elemental damage",
    itens: [
      {
        name: "Fiery Heart",
        qtty: 25,
        icon: "/images/imbuiments/scorch/Fiery_Heart.gif",
        type: "basic",
        amount: 10,
        chance: null,
      },
      {
        name: "Green Dragon Scale",
        qtty: 5,
        icon: "/images/imbuiments/scorch/Green_Dragon_Scale.gif",
        type: "intricate",
        amount: 25,
        chance: null,
      },
      {
        name: "Demon Horn",
        qtty: 5,
        icon: "/images/imbuiments/scorch/Demon_Horn.gif",
        type: "powerful",
        amount: 50,
        chance: null,
      },
    ],
  },
  {
    name: "Venom",
    icon: "/images/imbuiments/venom/Venom.gif",
    category: "elemental damage",
    itens: [
      {
        name: "Swamp Grass",
        qtty: 25,
        icon: "/images/imbuiments/venom/Swamp_Grass.gif",
        type: "basic",
        amount: 10,
        chance: null,
      },
      {
        name: "Poisonous Slime",
        qtty: 20,
        icon: "/images/imbuiments/venom/Poisonous_Slime.gif",
        type: "intricate",
        amount: 25,
        chance: null,
      },
      {
        name: "Slime Heart",
        qtty: 2,
        icon: "/images/imbuiments/venom/Slime_Heart.gif",
        type: "powerful",
        amount: 50,
        chance: null,
      },
    ],
  },
];
