export const TIMED_ITENS = [
  {
    id: "mmp-0",
    name: "Mastermind Potion",
    duration: 600,
    icon: "/images/itens-timer/Mastermind_Potion.gif",
    vocation: ["ed", "ms"],
  },
  {
    id: "rorp-1",
    name: "Ring of Red Plasma",
    duration: 1800,
    icon: "/images/itens-timer/Ring_of_Red_Plasma.gif",
    vocation: ["ek"],
  },
  {
    id: "corp-2",
    name: "Collar of Red Plasma",
    duration: 1800,
    icon: "/images/itens-timer/Collar_of_Red_Plasma.gif",
    vocation: ["ek"],
  },
  {
    id: "robp-3",
    name: "Ring of Blue Plasma",
    duration: 1800,
    icon: "/images/itens-timer/Ring_of_Blue_Plasma.gif",
    vocation: ["rp"],
  },
  {
    id: "cobp-4",
    name: "Collar of Blue Plasma",
    duration: 1800,
    icon: "/images/itens-timer/Collar_of_Blue_Plasma.gif",
    vocation: ["rp"],
  },
  {
    id: "rogp-6",
    name: "Collar of Green Plasma",
    duration: 1800,
    icon: "/images/itens-timer/Collar_of_Green_Plasma.gif",
    vocation: ["ms", "ed"],
  },
  {
    id: "cogp-7",
    name: "Ring of Green Plasma",
    duration: 1800,
    icon: "/images/itens-timer/Ring_of_Green_Plasma.gif",
    vocation: ["ms", "ed"],
  },

  {
    id: "ess-13",
    name: "Enchanted Sleep Shawl",
    duration: 3600,
    icon: "/images/itens-timer/Enchanted_Sleep_Shawl.gif",
    vocation: ["rp"],
  },
  {
    id: "eta-8",
    name: "Enchanted Theurgic Amulet",
    duration: 7200,
    icon: "/images/itens-timer/Enchanted_Theurgic_Amulet.gif",
    vocation: ["ms", "ed"],
  },
  
  {
    id: "cstr-10",
    name: "Charged Spiritthorn Ring",
    duration: 10800,
    icon: "/images/itens-timer/Charged_Spiritthorn_Ring.gif",
    vocation: ["ek"],
  },
  {
    id: "cas-11",
    name: "Charged Arcanomancer Sigil",
    duration: 10800,
    icon: "/images/itens-timer/Charged_Arcanomancer_Sigil.gif",
    vocation: ["ms"],
  },
  {
    id: "fwsp-12",
    name: "Flask with Snake Poison",
    duration: 1800,
    icon: "/images/itens-timer/Flask_with_Snake_Poison.gif",
    vocation: ["ms", "ek", "ed","rp"],
  },
  {
    id: "prisr-9",
    name: "Prismatic Ring",
    duration: 3600,
    icon: "/images/itens-timer/Prismatic_Ring.gif",
    vocation: ["ms", "ek", "ed","rp"],
  },
];
